package GUI;

import CUSTOM.DraggableRoundPanel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout;
import java.awt.FlowLayout;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Image;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.LayoutStyle.ComponentPlacement;
import BEAN.DanhMucBean;
import BUS.Controller;
import java.awt.Cursor;
import javax.swing.JPopupMenu;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import java.awt.Dimension;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class HomeGui extends javax.swing.JFrame {

    /**
     * Creates new form HomeGui
     */
    public HomeGui() {
        initComponents();
        initController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        draggableRoundPanel4 = new CUSTOM.DraggableRoundPanel();
        draggableRoundPanel5 = new CUSTOM.DraggableRoundPanel();
        draggableRoundPanel6 = new CUSTOM.DraggableRoundPanel();
        draggableRoundPanel6.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1361, 725));
        setSize(new java.awt.Dimension(1361, 725));
        
        pUserInfo = new JPanel();

        javax.swing.GroupLayout draggableRoundPanel4Layout = new javax.swing.GroupLayout(draggableRoundPanel4);
        draggableRoundPanel4Layout.setHorizontalGroup(
        	draggableRoundPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, draggableRoundPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(pUserInfo, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        			.addContainerGap())
        );
        draggableRoundPanel4Layout.setVerticalGroup(
        	draggableRoundPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(draggableRoundPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(pUserInfo, GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        			.addContainerGap())
        );
        
        lblStaffName = new JLabel("nhanvien.TenNV");
        lblStaffName.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        lblStaffName.setFont(new Font("Tahoma", Font.BOLD, 16));
        
        lblRole = new JLabel("chucvu.TenCV");
        lblRole.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
        lblRole.setFont(new Font("Tahoma", Font.PLAIN, 14));
        
        btnSettings = new JButton();
        btnSettings.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		popupSettings.show(btnSettings, 0, btnSettings.getPreferredSize().height);
        	}
        });
        btnSettings.setOpaque(false);
        btnSettings.setPreferredSize(new Dimension(24, 24));
        btnSettings.setMaximumSize(new Dimension(24, 24));
        btnSettings.setMinimumSize(new Dimension(24, 24));
        ImageIcon settingIcon = new ImageIcon(HomeGui.class.getResource("/Images/settings.png"));
        Image smallSettingIcon = settingIcon.getImage().getScaledInstance(16, 16, java.awt.Image.SCALE_SMOOTH);
        settingIcon = new ImageIcon(smallSettingIcon);
        btnSettings.setIcon(settingIcon);
        GroupLayout gl_pUserInfo = new GroupLayout(pUserInfo);
        gl_pUserInfo.setHorizontalGroup(
        	gl_pUserInfo.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_pUserInfo.createSequentialGroup()
        			.addComponent(lblRole)
        			.addContainerGap(78, Short.MAX_VALUE))
        		.addGroup(gl_pUserInfo.createSequentialGroup()
        			.addComponent(lblStaffName)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnSettings, 0, 25, Short.MAX_VALUE)
        			.addGap(6))
        );
        gl_pUserInfo.setVerticalGroup(
        	gl_pUserInfo.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_pUserInfo.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_pUserInfo.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btnSettings, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblStaffName))
        			.addPreferredGap(ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        			.addComponent(lblRole, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        			.addGap(16))
        );
        
        popupSettings = new JPopupMenu();
        popupSettings.setFont(new Font("Tahoma", Font.PLAIN, 12));
        addPopup(btnSettings, popupSettings);
        popupSettings.setLabel("");
        
        btnLogOut = new JMenuItem("Đăng xuất");
        btnLogOut.setFont(new Font("Arial", Font.PLAIN, 12));
        btnLogOut.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnLogOutActionPerformed(e);
        	}
        });
        btnLogOut.setIcon(new ImageIcon(HomeGui.class.getResource("/Images/logout.png")));
        popupSettings.add(btnLogOut);
        
        btnExit = new JMenuItem("Thoát");
        btnExit.setFont(new Font("Arial", Font.PLAIN, 12));
        btnExit.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnExitActionPerformed(e);
        	}
        });
        btnExit.setIcon(new ImageIcon(HomeGui.class.getResource("/Images/turn-off.png")));
        popupSettings.add(btnExit);
        pUserInfo.setLayout(gl_pUserInfo);
        draggableRoundPanel4.setLayout(draggableRoundPanel4Layout);

        javax.swing.GroupLayout draggableRoundPanel6Layout = new javax.swing.GroupLayout(draggableRoundPanel6);
        draggableRoundPanel6Layout.setHorizontalGroup(
        	draggableRoundPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 1131, Short.MAX_VALUE)
        );
        draggableRoundPanel6Layout.setVerticalGroup(
        	draggableRoundPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 664, Short.MAX_VALUE)
        );
        draggableRoundPanel6.setLayout(draggableRoundPanel6Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(draggableRoundPanel5, 0, 0, Short.MAX_VALUE)
        				.addComponent(draggableRoundPanel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(draggableRoundPanel6, GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(draggableRoundPanel6, GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(draggableRoundPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(draggableRoundPanel5, GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);
        draggableRoundPanel5.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        
        pHoaDon = new JPanel();
        draggableRoundPanel5.add(pHoaDon);
        
        lblHoaDon = new JLabel("Hoá đơn");
        lblHoaDon.setForeground(new Color(0, 0, 0));
        lblHoaDon.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblHoaDon.setHorizontalAlignment(SwingConstants.CENTER);
        lblHoaDon.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pHoaDon = new GroupLayout(pHoaDon);
        gl_pHoaDon.setHorizontalGroup(
        	gl_pHoaDon.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblHoaDon, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pHoaDon.setVerticalGroup(
        	gl_pHoaDon.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblHoaDon, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pHoaDon.setLayout(gl_pHoaDon);
        
        pKhachHang = new JPanel();
        pKhachHang.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        draggableRoundPanel5.add(pKhachHang);
        
        lblKhachHang = new JLabel("Khách hàng");
        lblKhachHang.setForeground(new Color(0, 0, 0));
        lblKhachHang.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblKhachHang.setHorizontalAlignment(SwingConstants.CENTER);
        lblKhachHang.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pKhachHang = new GroupLayout(pKhachHang);
        gl_pKhachHang.setHorizontalGroup(
        	gl_pKhachHang.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblKhachHang, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pKhachHang.setVerticalGroup(
        	gl_pKhachHang.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblKhachHang, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pKhachHang.setLayout(gl_pKhachHang);
        
        pNhanVien = new JPanel();
        pNhanVien.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        draggableRoundPanel5.add(pNhanVien);
        
        lblNhanVien = new JLabel("Nhân viên");
        lblNhanVien.setForeground(new Color(0, 0, 0));
        lblNhanVien.setHorizontalAlignment(SwingConstants.CENTER);
        lblNhanVien.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pNhanVien = new GroupLayout(pNhanVien);
        gl_pNhanVien.setHorizontalGroup(
        	gl_pNhanVien.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblNhanVien, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pNhanVien.setVerticalGroup(
        	gl_pNhanVien.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblNhanVien, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pNhanVien.setLayout(gl_pNhanVien);
        
        pKhuyenMai = new JPanel();
        pKhuyenMai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        draggableRoundPanel5.add(pKhuyenMai);
        
        lblKhuyenMai = new JLabel("Khuyến mãi");
        lblKhuyenMai.setForeground(new Color(0, 0, 0));
        lblKhuyenMai.setHorizontalAlignment(SwingConstants.CENTER);
        lblKhuyenMai.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pKhuyenMai = new GroupLayout(pKhuyenMai);
        gl_pKhuyenMai.setHorizontalGroup(
        	gl_pKhuyenMai.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblKhuyenMai, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pKhuyenMai.setVerticalGroup(
        	gl_pKhuyenMai.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblKhuyenMai, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pKhuyenMai.setLayout(gl_pKhuyenMai);
        
        pSanPham = new JPanel();
        pSanPham.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        draggableRoundPanel5.add(pSanPham);
        
        lblSanPham = new JLabel("Sản phẩm");
        lblSanPham.setForeground(new Color(0, 0, 0));
        lblSanPham.setHorizontalAlignment(SwingConstants.CENTER);
        lblSanPham.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pSanPham = new GroupLayout(pSanPham);
        gl_pSanPham.setHorizontalGroup(
        	gl_pSanPham.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblSanPham, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pSanPham.setVerticalGroup(
        	gl_pSanPham.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblSanPham, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pSanPham.setLayout(gl_pSanPham);
        
        pPhanQuyen = new JPanel();
        pPhanQuyen.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        draggableRoundPanel5.add(pPhanQuyen);
        
        lblPhanQuyen = new JLabel("Phân quyền");
        lblPhanQuyen.setForeground(new Color(0, 0, 0));
        lblPhanQuyen.setHorizontalAlignment(SwingConstants.CENTER);
        lblPhanQuyen.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pPhanQuyen = new GroupLayout(pPhanQuyen);
        gl_pPhanQuyen.setHorizontalGroup(
        	gl_pPhanQuyen.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblPhanQuyen, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pPhanQuyen.setVerticalGroup(
        	gl_pPhanQuyen.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblPhanQuyen, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pPhanQuyen.setLayout(gl_pPhanQuyen);
        
        pThongKe = new JPanel();
        pThongKe.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        draggableRoundPanel5.add(pThongKe);
        
        lblThongKe = new JLabel("Thống kê");
        lblThongKe.setForeground(new Color(0, 0, 0));
        lblThongKe.setHorizontalAlignment(SwingConstants.CENTER);
        lblThongKe.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pThongKe = new GroupLayout(pThongKe);
        gl_pThongKe.setHorizontalGroup(
        	gl_pThongKe.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblThongKe, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pThongKe.setVerticalGroup(
        	gl_pThongKe.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblThongKe, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pThongKe.setLayout(gl_pThongKe);
        
        pNhapHang = new JPanel();
        pNhapHang.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        draggableRoundPanel5.add(pNhapHang);
        
        lblNhapHang = new JLabel("Nhập hàng");
        lblNhapHang.setForeground(new Color(0, 0, 0));
        lblNhapHang.setHorizontalAlignment(SwingConstants.CENTER);
        lblNhapHang.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pNhapHang = new GroupLayout(pNhapHang);
        gl_pNhapHang.setHorizontalGroup(
        	gl_pNhapHang.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblNhapHang, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pNhapHang.setVerticalGroup(
        	gl_pNhapHang.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblNhapHang, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pNhapHang.setLayout(gl_pNhapHang);
        
        pTaiKhoan = new JPanel();
        draggableRoundPanel5.add(pTaiKhoan);
        
        lblTaiKhoan = new JLabel("Tài khoản");
        lblTaiKhoan.setForeground(new Color(0, 0, 0));
        lblTaiKhoan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblTaiKhoan.setHorizontalAlignment(SwingConstants.CENTER);
        lblTaiKhoan.setFont(new Font("Tahoma", Font.BOLD, 14));
        GroupLayout gl_pTaiKhoan = new GroupLayout(pTaiKhoan);
        gl_pTaiKhoan.setHorizontalGroup(
        	gl_pTaiKhoan.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 168, Short.MAX_VALUE)
        		.addComponent(lblTaiKhoan, GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
        );
        gl_pTaiKhoan.setVerticalGroup(
        	gl_pTaiKhoan.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(lblTaiKhoan, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        pTaiKhoan.setLayout(gl_pTaiKhoan);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initController() {
    	Controller controller = new Controller(draggableRoundPanel6);
        List <DanhMucBean> listItem = new ArrayList();
        listItem.add(new DanhMucBean("HoaDon", pHoaDon, lblHoaDon));
        listItem.add(new DanhMucBean("KhachHang", pKhachHang, lblKhachHang));
        listItem.add(new DanhMucBean("NhanVien", pNhanVien, lblNhanVien));
        listItem.add(new DanhMucBean("KhuyenMai", pKhuyenMai, lblKhuyenMai));
        listItem.add(new DanhMucBean("SanPham", pSanPham, lblSanPham));
        listItem.add(new DanhMucBean("PhanQuyen", pPhanQuyen, lblPhanQuyen));
        listItem.add(new DanhMucBean("ThongKe", pThongKe, lblThongKe));
        listItem.add(new DanhMucBean("NhapHang", pNhapHang, lblNhapHang));
        listItem.add(new DanhMucBean("TaiKhoan", pTaiKhoan, lblTaiKhoan));
        controller.setEvent(listItem);
        controller.setView(pHoaDon, lblHoaDon);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	// set Windows look and feel
        try {
        	javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGui().setVisible(true);
            }
        });
    }
    
    public boolean isLoggedOut() {
		return loggedOut;
	}

	public void setLoggedOut(boolean loggedOut) {
		this.loggedOut = loggedOut;
	}
    
    private void btnLogOutActionPerformed(ActionEvent e) {
    	setLoggedOut(true);
    	dispose();
    }
    
    private void btnExitActionPerformed(ActionEvent e) {
    	dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CUSTOM.DraggableRoundPanel draggableRoundPanel4;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel5;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel6;
    private JPanel pTaiKhoan;
    private JLabel lblTaiKhoan;
    private JPanel pUserInfo;
    private JLabel lblStaffName;
    private JLabel lblRole;
    private JPanel pHoaDon;
    private JLabel lblHoaDon;
    private JPanel pKhachHang;
    private JLabel lblKhachHang;
    private JPanel pNhanVien;
    private JLabel lblNhanVien;
    private JPanel pKhuyenMai;
    private JLabel lblKhuyenMai;
    private JPanel pSanPham;
    private JLabel lblSanPham;
    private JPanel pPhanQuyen;
    private JLabel lblPhanQuyen;
    private JPanel pThongKe;
    private JLabel lblThongKe;
    private JPanel pNhapHang;
    private JLabel lblNhapHang;
    private JButton btnSettings;
    private JPopupMenu popupSettings;
    private JMenuItem btnLogOut;
    private JMenuItem btnExit;
	private static void addPopup(Component component, final JPopupMenu popup) {
		component.addMouseListener(new MouseAdapter() {
			public void mousePressed(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			public void mouseReleased(MouseEvent e) {
				if (e.isPopupTrigger()) {
					showMenu(e);
				}
			}
			private void showMenu(MouseEvent e) {
				popup.show(e.getComponent(), e.getX(), e.getY());
			}
		});
	}
	private boolean loggedOut = false;
}
