/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.LayoutManager;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;
import BUS.Coupon_BUS;
import CUSTOM.KiemTra;
import DTO.ChucVu;
import DTO.Coupon;
import DTO.NhanVien;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class KhuyenMaiJPanel extends javax.swing.JPanel {
    private KiemTra kt=new KiemTra();
    private Coupon_BUS cpBUS=new Coupon_BUS();
    /**
     * Creates new form KhuyenMaiJPanel
     */
    public KhuyenMaiJPanel() throws ClassNotFoundException, SQLException {
        initComponents();
        jTable3.setDefaultEditor(Object.class, null);
        try {
            LoadCouponList();
        } catch (SQLException ex) {
            Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoadRowValueToTextFD(jTable3);
        LoadComboBox();
    }
    
    public KhuyenMaiJPanel (NhanVien user, ChucVu permission) throws ClassNotFoundException, SQLException {
        initComponents();
        jTable3.setDefaultEditor(Object.class, null);
        try {
            LoadCouponList();
        } catch (SQLException ex) {
            Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        LoadRowValueToTextFD(jTable3);
        LoadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void LoadCouponList() throws SQLException, ClassNotFoundException
    {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã Coupon");
        dtm.addColumn("Code");
        dtm.addColumn("Tổng lượt áp dụng");
        dtm.addColumn("Tổng lượt đã dùng");
        dtm.addColumn("Mã KMHD");
        jTable3.setModel(dtm);
        ArrayList<Coupon> arr = new ArrayList<Coupon>();
        arr = cpBUS.getAllCouponNotDeleted();
        for(int i = 0; i < arr.size(); i++){
                Coupon cp = arr.get(i);
                int id = cp.getMaCP();
                String cd = cp.getCode();
                int tlad = cp.getTongLuotApDung();
                int tldd = cp.getTongLuotDaDung();
                int makmhd = cp.getMaKMHD();
                Object[] row = {id,cd,tlad,tldd,makmhd};
                dtm.addRow(row);
        }
    }
    
    public void LoadRowValueToTextFD(JTable table)
    {
        table.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example
            int viewRow = table.getSelectedRow();
            if (!event.getValueIsAdjusting() && viewRow != -1) {
                System.out.println(table.getValueAt(table.getSelectedRow(), 0).toString());
                int viewrow=table.convertRowIndexToModel(viewRow);
                jTextField20.setText(table.getModel().getValueAt(viewrow, 0).toString());
                jTextField19.setText(table.getModel().getValueAt(viewrow, 1).toString());
                jTextField29.setText(table.getModel().getValueAt(viewrow, 2).toString());
                jTextField30.setText(table.getModel().getValueAt(viewrow, 3).toString());
                jComboBox17.setSelectedItem(table.getModel().getValueAt(viewrow, 4).toString());
            }
        }
    });
    }
    
    public void LoadComboBox() throws SQLException, ClassNotFoundException
    {
        jComboBox17.setModel(new DefaultComboBoxModel(cpBUS.getDistincMaKMHD()));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDatePickerUtil1 = new net.sourceforge.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new net.sourceforge.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil3 = new net.sourceforge.jdatepicker.util.JDatePickerUtil();
        draggableRoundPanel1 = new CUSTOM.DraggableRoundPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        draggableRoundPanel3 = new CUSTOM.DraggableRoundPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        draggableRoundPanel4 = new CUSTOM.DraggableRoundPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        draggableRoundPanel19 = new CUSTOM.DraggableRoundPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jComboBox21 = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        jDateChooser15 = new com.toedter.calendar.JDateChooser();
        jLabel61 = new javax.swing.JLabel();
        jDateChooser16 = new com.toedter.calendar.JDateChooser();
        jPanel21 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jPanel22 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jTextField43 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        draggableRoundPanel7 = new CUSTOM.DraggableRoundPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        draggableRoundPanel12 = new CUSTOM.DraggableRoundPanel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jTextField11 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        draggableRoundPanel16 = new CUSTOM.DraggableRoundPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jDateChooser11 = new com.toedter.calendar.JDateChooser();
        jLabel50 = new javax.swing.JLabel();
        jDateChooser12 = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        draggableRoundPanel10 = new CUSTOM.DraggableRoundPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        draggableRoundPanel13 = new CUSTOM.DraggableRoundPanel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jTextField12 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        draggableRoundPanel17 = new CUSTOM.DraggableRoundPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jComboBox17 = new javax.swing.JComboBox<>();
        jTextField20 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1155, 725));
        setLayout(new java.awt.BorderLayout());

        draggableRoundPanel1.setMinimumSize(new java.awt.Dimension(800, 400));
        draggableRoundPanel1.setPreferredSize(new java.awt.Dimension(1155, 725));
        draggableRoundPanel1.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 400));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1155, 713));

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.setLayout(new java.awt.BorderLayout(15,15));

        draggableRoundPanel3.setPreferredSize(new java.awt.Dimension(1143, 50));
        draggableRoundPanel3.setLayout(new java.awt.BorderLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(72, 22));
        jComboBox1.setPreferredSize(new java.awt.Dimension(130, 72));
        draggableRoundPanel3.add(jComboBox1, java.awt.BorderLayout.WEST);

        jTextField1.setMaximumSize(new java.awt.Dimension(64, 15));
        jTextField1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 15));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        draggableRoundPanel3.add(jTextField1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Tìm kiếm");
        jButton1.setPreferredSize(new java.awt.Dimension(90, 15));
        draggableRoundPanel3.add(jButton1, java.awt.BorderLayout.LINE_END);

        jPanel1.add(draggableRoundPanel3, java.awt.BorderLayout.PAGE_START);

        draggableRoundPanel4.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        draggableRoundPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(draggableRoundPanel4, java.awt.BorderLayout.CENTER);

        draggableRoundPanel19.setLayout(new java.awt.GridBagLayout());

        jPanel14.setLayout(new java.awt.GridBagLayout());

        jLabel57.setText("Mã KMHD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel14.add(jLabel57, gridBagConstraints);

        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox21.setMinimumSize(new java.awt.Dimension(82, 22));
        jComboBox21.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel14.add(jComboBox21, gridBagConstraints);

        jLabel60.setText("Ngày bắt đầu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel14.add(jLabel60, gridBagConstraints);

        jDateChooser15.setMinimumSize(new java.awt.Dimension(82, 22));
        jDateChooser15.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel14.add(jDateChooser15, gridBagConstraints);

        jLabel61.setText("Ngày kết thúc:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel14.add(jLabel61, gridBagConstraints);

        jDateChooser16.setMinimumSize(new java.awt.Dimension(82, 22));
        jDateChooser16.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel14.add(jDateChooser16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        draggableRoundPanel19.add(jPanel14, gridBagConstraints);

        jPanel21.setLayout(new java.awt.GridBagLayout());

        jLabel45.setText("Phần trăm giảm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel21.add(jLabel45, gridBagConstraints);

        jTextField38.setMinimumSize(new java.awt.Dimension(72, 22));
        jTextField38.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel21.add(jTextField38, gridBagConstraints);

        jLabel46.setText("Đơn hàng tối thiểu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel21.add(jLabel46, gridBagConstraints);

        jTextField39.setMinimumSize(new java.awt.Dimension(72, 22));
        jTextField39.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel21.add(jTextField39, gridBagConstraints);

        jLabel47.setText("Tên khuyến mãi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel21.add(jLabel47, gridBagConstraints);

        jTextField40.setMinimumSize(new java.awt.Dimension(72, 22));
        jTextField40.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel21.add(jTextField40, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        draggableRoundPanel19.add(jPanel21, gridBagConstraints);

        jPanel22.setLayout(new java.awt.GridBagLayout());

        jLabel62.setText("Tổng lượt áp dụng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel22.add(jLabel62, gridBagConstraints);

        jTextField41.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField41.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel22.add(jTextField41, gridBagConstraints);

        jLabel63.setText("Tổng lượt đã dùng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel22.add(jLabel63, gridBagConstraints);

        jTextField42.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField42.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel22.add(jTextField42, gridBagConstraints);

        jLabel64.setText("Số tiền giảm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel22.add(jLabel64, gridBagConstraints);

        jTextField43.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField43.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel22.add(jTextField43, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        draggableRoundPanel19.add(jPanel22, gridBagConstraints);

        jPanel23.setMinimumSize(new java.awt.Dimension(72, 111));
        jPanel23.setPreferredSize(new java.awt.Dimension(72, 120));
        jPanel23.setLayout(new java.awt.GridBagLayout());

        jButton37.setText("Thêm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel23.add(jButton37, gridBagConstraints);

        jButton38.setText("Sửa");
        jButton38.setPreferredSize(new java.awt.Dimension(63, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel23.add(jButton38, gridBagConstraints);

        jButton39.setText("Xóa");
        jButton39.setPreferredSize(new java.awt.Dimension(63, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel23.add(jButton39, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 0);
        draggableRoundPanel19.add(jPanel23, gridBagConstraints);

        jPanel1.add(draggableRoundPanel19, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Khuyến mãi hóa đơn", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.setLayout(new java.awt.BorderLayout(15,15));

        draggableRoundPanel7.setLayout(new java.awt.BorderLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        draggableRoundPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(draggableRoundPanel7, java.awt.BorderLayout.CENTER);

        draggableRoundPanel12.setPreferredSize(new java.awt.Dimension(1143, 50));
        draggableRoundPanel12.setLayout(new java.awt.BorderLayout());

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox10.setMaximumSize(new java.awt.Dimension(72, 22));
        jComboBox10.setPreferredSize(new java.awt.Dimension(130, 72));
        draggableRoundPanel12.add(jComboBox10, java.awt.BorderLayout.WEST);

        jTextField11.setMaximumSize(new java.awt.Dimension(64, 15));
        jTextField11.setMinimumSize(new java.awt.Dimension(64, 15));
        jTextField11.setPreferredSize(new java.awt.Dimension(64, 15));
        draggableRoundPanel12.add(jTextField11, java.awt.BorderLayout.CENTER);

        jButton17.setText("Tìm kiếm");
        jButton17.setPreferredSize(new java.awt.Dimension(90, 15));
        draggableRoundPanel12.add(jButton17, java.awt.BorderLayout.LINE_END);

        jPanel2.add(draggableRoundPanel12, java.awt.BorderLayout.NORTH);

        draggableRoundPanel16.setLayout(new java.awt.GridBagLayout());

        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel48.setText("Mã KMSP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel8.add(jLabel48, gridBagConstraints);

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox19.setMinimumSize(new java.awt.Dimension(82, 22));
        jComboBox19.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel8.add(jComboBox19, gridBagConstraints);

        jLabel49.setText("Ngày bắt đầu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel8.add(jLabel49, gridBagConstraints);

        jDateChooser11.setMinimumSize(new java.awt.Dimension(82, 22));
        jDateChooser11.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel8.add(jDateChooser11, gridBagConstraints);

        jLabel50.setText("Ngày kết thúc:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel8.add(jLabel50, gridBagConstraints);

        jDateChooser12.setMinimumSize(new java.awt.Dimension(82, 22));
        jDateChooser12.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel8.add(jDateChooser12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        draggableRoundPanel16.add(jPanel8, gridBagConstraints);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jLabel36.setText("Phần trăm giảm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel9.add(jLabel36, gridBagConstraints);

        jTextField26.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField26.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel9.add(jTextField26, gridBagConstraints);

        jLabel37.setText("Số tiền giảm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel9.add(jLabel37, gridBagConstraints);

        jTextField27.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField27.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel9.add(jTextField27, gridBagConstraints);

        jLabel38.setText("Mã SP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel9.add(jLabel38, gridBagConstraints);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox13.setMinimumSize(new java.awt.Dimension(82, 22));
        jComboBox13.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel9.add(jComboBox13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        draggableRoundPanel16.add(jPanel9, gridBagConstraints);

        jPanel16.setLayout(new java.awt.GridBagLayout());

        jLabel51.setText("Tổng lượt áp dụng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel16.add(jLabel51, gridBagConstraints);

        jTextField33.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField33.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel16.add(jTextField33, gridBagConstraints);

        jLabel52.setText("Tổng lượt đã dùng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel16.add(jLabel52, gridBagConstraints);

        jTextField34.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField34.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel16.add(jTextField34, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        draggableRoundPanel16.add(jPanel16, gridBagConstraints);

        jPanel17.setMinimumSize(new java.awt.Dimension(72, 111));
        jPanel17.setPreferredSize(new java.awt.Dimension(72, 120));
        jPanel17.setLayout(new java.awt.GridBagLayout());

        jButton31.setText("Thêm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel17.add(jButton31, gridBagConstraints);

        jButton32.setText("Sửa");
        jButton32.setMinimumSize(new java.awt.Dimension(63, 25));
        jButton32.setPreferredSize(new java.awt.Dimension(63, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel17.add(jButton32, gridBagConstraints);

        jButton33.setText("Xóa");
        jButton33.setMinimumSize(new java.awt.Dimension(63, 25));
        jButton33.setPreferredSize(new java.awt.Dimension(63, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel17.add(jButton33, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 0);
        draggableRoundPanel16.add(jPanel17, gridBagConstraints);

        jPanel2.add(draggableRoundPanel16, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Khuyến mãi sản phẩm", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.setLayout(new java.awt.BorderLayout(15,15));

        draggableRoundPanel10.setLayout(new java.awt.BorderLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        draggableRoundPanel10.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel3.add(draggableRoundPanel10, java.awt.BorderLayout.CENTER);

        draggableRoundPanel13.setPreferredSize(new java.awt.Dimension(1143, 50));
        draggableRoundPanel13.setLayout(new java.awt.BorderLayout());

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox11.setMaximumSize(new java.awt.Dimension(72, 22));
        jComboBox11.setPreferredSize(new java.awt.Dimension(130, 72));
        draggableRoundPanel13.add(jComboBox11, java.awt.BorderLayout.WEST);

        jTextField12.setMaximumSize(new java.awt.Dimension(64, 15));
        jTextField12.setMinimumSize(new java.awt.Dimension(64, 15));
        jTextField12.setPreferredSize(new java.awt.Dimension(64, 15));
        draggableRoundPanel13.add(jTextField12, java.awt.BorderLayout.CENTER);

        jButton18.setText("Tìm kiếm");
        jButton18.setPreferredSize(new java.awt.Dimension(90, 15));
        draggableRoundPanel13.add(jButton18, java.awt.BorderLayout.LINE_END);

        jPanel3.add(draggableRoundPanel13, java.awt.BorderLayout.NORTH);

        draggableRoundPanel17.setLayout(new java.awt.GridBagLayout());

        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel14.setText("Mã CP:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel11.add(jLabel14, gridBagConstraints);

        jLabel22.setText("Code:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel11.add(jLabel22, gridBagConstraints);

        jTextField19.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField19.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel11.add(jTextField19, gridBagConstraints);

        jLabel40.setText("Mã KMHD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel11.add(jLabel40, gridBagConstraints);

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox17.setMinimumSize(new java.awt.Dimension(82, 22));
        jComboBox17.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel11.add(jComboBox17, gridBagConstraints);

        jTextField20.setEditable(false);
        jTextField20.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField20.setPreferredSize(new java.awt.Dimension(160, 22));
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel11.add(jTextField20, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        draggableRoundPanel17.add(jPanel11, gridBagConstraints);

        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel41.setText("Tổng lượt áp dụng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel12.add(jLabel41, gridBagConstraints);

        jTextField29.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField29.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 20);
        jPanel12.add(jTextField29, gridBagConstraints);

        jLabel42.setText("Tổng lượt đã dùng:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel12.add(jLabel42, gridBagConstraints);

        jTextField30.setMinimumSize(new java.awt.Dimension(82, 22));
        jTextField30.setPreferredSize(new java.awt.Dimension(160, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel12.add(jTextField30, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        draggableRoundPanel17.add(jPanel12, gridBagConstraints);

        jPanel13.setLayout(new java.awt.GridBagLayout());

        jButton25.setText("Thêm");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel13.add(jButton25, gridBagConstraints);

        jButton26.setText("Sửa");
        jButton26.setMinimumSize(new java.awt.Dimension(63, 25));
        jButton26.setPreferredSize(new java.awt.Dimension(63, 25));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel13.add(jButton26, gridBagConstraints);

        jButton27.setText("Xóa");
        jButton27.setMinimumSize(new java.awt.Dimension(63, 25));
        jButton27.setPreferredSize(new java.awt.Dimension(63, 25));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel13.add(jButton27, gridBagConstraints);

        jButton28.setText("Xóa nhập");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        jPanel13.add(jButton28, gridBagConstraints);

        jButton29.setText("Refesh");
        jButton29.setMinimumSize(new java.awt.Dimension(67, 25));
        jButton29.setPreferredSize(new java.awt.Dimension(67, 25));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        jPanel13.add(jButton29, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 0);
        draggableRoundPanel17.add(jPanel13, gridBagConstraints);

        jPanel3.add(draggableRoundPanel17, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Coupon", jPanel3);

        draggableRoundPanel1.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(draggableRoundPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
            if(jTextField20.getText().isBlank()||jTextField19.getText().isBlank()||jTextField29.getText().isBlank()||jTextField30.getText().isBlank())
            {
                JOptionPane.showMessageDialog(this, "Vui lòng không bỏ trống hoặc chỉ có khoảng cách!");
            }
            else if(!kt.KTKhoangCach(jTextField19.getText())||!kt.KTKhoangCach(jTextField29.getText())||!kt.KTKhoangCach(jTextField30.getText()))
            {
                JOptionPane.showMessageDialog(this, "Vui lòng không được có khoảng cách!");
            }
            else if(!kt.KTSo(jTextField29.getText())||!kt.KTSo(jTextField30.getText()))
            {
                JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập số!");
            }
            else if(!kt.KTKyTuDacBietKhongKhoangCach(jTextField19.getText()))
            {
                JOptionPane.showMessageDialog(this, "Vui lòng chỉ chữ với ký tự đặc biệt!");
            }
            else try {
                if(cpBUS.hasCode(jTextField19.getText())!=false)
                {
                    JOptionPane.showMessageDialog(this, "Trùng code!");
                }
                else
                {
                    Coupon cp=new Coupon();
                    cp.setCode(jTextField19.getText());
                    cp.setMaKMHD(Integer.parseInt(jComboBox17.getItemAt(jComboBox17.getSelectedIndex())));
                    cp.setTongLuotApDung(Integer.parseInt(jTextField29.getText()));
                    cp.setTongLuotDaDung(Integer.parseInt(jTextField30.getText()));
                    cp.setIsDeleted(0);
                    try {
                        cpBUS.addCoupon(cp);
                    } catch (SQLException ex) {
                        Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        LoadCouponList();
                        LoadComboBox();
                    } catch (SQLException ex) {
                        Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        if(jTable3.getSelectedRows().length==0)
        {
            JOptionPane.showMessageDialog(this, "Chưa chọn hàng để sửa!");
        }
        else if(jTextField20.getText().isBlank()||jTextField19.getText().isBlank()||jTextField29.getText().isBlank()||jTextField30.getText().isBlank())
            {
                JOptionPane.showMessageDialog(this, "Vui lòng không bỏ trống hoặc chỉ có khoảng cách!");
            }
            else if(!kt.KTKhoangCach(jTextField19.getText())||!kt.KTKhoangCach(jTextField29.getText())||!kt.KTKhoangCach(jTextField30.getText()))
            {
                JOptionPane.showMessageDialog(this, "Vui lòng không được có khoảng cách!");
            }
            else if(!kt.KTSo(jTextField29.getText())||!kt.KTSo(jTextField30.getText()))
            {
                JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập số!");
            }
            else if(!kt.KTKyTuDacBietKhongKhoangCach(jTextField19.getText()))
            {
                JOptionPane.showMessageDialog(this, "Vui lòng chỉ chữ với ký tự đặc biệt!");
            }
            else{
                    Coupon cp=new Coupon();
                    cp.setMaCP(Integer.parseInt(jTextField20.getText()));
                    cp.setCode(jTextField19.getText());
                    cp.setMaKMHD(Integer.parseInt(jComboBox17.getItemAt(jComboBox17.getSelectedIndex())));
                    cp.setTongLuotApDung(Integer.parseInt(jTextField29.getText()));
                    cp.setTongLuotDaDung(Integer.parseInt(jTextField30.getText()));
                    cp.setIsDeleted(0);
                    try {
                        cpBUS.updateCoupon(cp);
                    } catch (SQLException ex) {
                        Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        LoadCouponList();
                        LoadComboBox();
                    } catch (SQLException ex) {
                        Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
            }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        if(jTable3.getSelectedRows().length==0)
        {
            JOptionPane.showMessageDialog(this, "Chưa chọn hàng để xóa!");
        }
        else for(int i=0;i<jTable3.getSelectedRows().length;i++)
        {
            try {
                cpBUS.deleteCoupon(Integer.parseInt(jTable3.getModel().getValueAt(jTable3.getSelectedRows()[i], 0).toString()));
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            LoadCouponList();
            LoadComboBox();
        } catch (SQLException ex) {
            Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        jTable3.getSelectionModel().clearSelection();
        jTextField20.setText("");
        jTextField19.setText("");
        jTextField29.setText("");
        jTextField30.setText("");
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        try {
            // TODO add your handling code here:
            LoadCouponList();
            LoadComboBox();
        } catch (SQLException ex) {
            Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KhuyenMaiJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton29ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CUSTOM.DraggableRoundPanel draggableRoundPanel1;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel10;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel12;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel13;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel16;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel17;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel19;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel3;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel4;
    private CUSTOM.DraggableRoundPanel draggableRoundPanel7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox21;
    private com.toedter.calendar.JDateChooser jDateChooser11;
    private com.toedter.calendar.JDateChooser jDateChooser12;
    private com.toedter.calendar.JDateChooser jDateChooser15;
    private com.toedter.calendar.JDateChooser jDateChooser16;
    private net.sourceforge.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private net.sourceforge.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private net.sourceforge.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    // End of variables declaration//GEN-END:variables
}
